version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
