# Use Node JS v16.x as base image
FROM node:16


# Create server directory inside image
WORKDIR /app

# Ensure there is no default entrypoint
ENTRYPOINT []

# Copy the source code (src -> /app)
# node_modules directory is ignored via .dockerignore file
COPY . .

# Install dependencies (inside the container)
RUN npm install

RUN which npm && npm --version


# Expose server port
EXPOSE 3000

# Start server using npm script
CMD [ "npm", "run", "start" ]
